### Задачи для практики из урока

- 10 самых старых фильмов.
- Сколько фильмов вышло в 1994 году.
- Фильмы Франции с рейтингом выше 8.0.
- Фильмы с названием длиннее 15 символов.
- Сколько фильмов снято в каждой стране (value_counts).
- Топ-5 режиссёров по числу фильмов в рейтинге.
- 
И ещё немного практики:

- Три года, в которые вышло больше всего фильмов.
- Фильмы, в описании которых встречается слово «любовь».
- Средний рейтинг фильмов до 1980 года и после 2000 года (результат — обе величины — сохранить и вывести с точностью до двух знаков запятой для удобства).

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../kinopoisk-top250.csv')
display(df.describe())  
display(df.info())

           rating         year  rating_ball
count  250.000000   250.000000   250.000000
mean   124.500000  1991.736000     8.231444
std     72.312977    19.015168     0.230376
min      0.000000  1921.000000     7.806000
25%     62.250000  1980.000000     8.063500
50%    124.500000  1997.500000     8.169000
75%    186.750000  2005.000000     8.355750
max    249.000000  2019.000000     9.111000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rating        250 non-null    int64
 1   movie         250 non-null    object
 2   year          250 non-null    int64
 3   country       250 non-null    object
 4   rating_ball   250 non-null    float64
 5   overview      250 non-null    object
 6   director      250 non-null    object
 7   screenwriter  250 non-null    object
 8   actors        250 non-null    object
 9   url_logo      250 non-null    object
dtypes: float64(1), int64(2), object(7)
memory usage: 19.7+ KB

None

Десять самых старых фильмов

In [9]:
ten_eldest = df.sort_values('year')[['movie', 'year']][:10]
display(ten_eldest)

                                movie  year
78                             Малыш   1921
221                Золотая лихорадка   1925
201                             Цирк   1928
45              Огни большого города   1931
121                    Новые времена   1936
89                  Унесенные ветром   1939
49           Эта замечательная жизнь   1947
234                Поющие под дождем   1952
88                  Римские каникулы   1953
157  В случае убийства набирайте «М»   1954

Сколько фильмов вышло в 1994 году.

In [17]:
films_in_1994 = df[df['year'] == 1994]
cnt = films_in_1994.shape[0]
display(cnt)

5

Фильмы Франции с рейтингом выше 8.0.

In [ ]:
france_good_films = df[(df['country'] == 'Франция') & (df['rating'] > 8.0)]
display(france_good_films)

Фильмы с названием длиннее 15 символов.