### Задачи для практики из урока

- 10 самых старых фильмов.
- Сколько фильмов вышло в 1994 году.
- Фильмы Франции с рейтингом выше 8.0.
- Фильмы с названием длиннее 15 символов.
- Сколько фильмов снято в каждой стране (value_counts).
- Топ-5 режиссёров по числу фильмов в рейтинге.
  
И ещё немного практики:

- Три года, в которые вышло больше всего фильмов.
- Фильмы, в описании которых встречается слово «любовь».
- Средний рейтинг фильмов до 1980 года и после 2000 года (результат — обе величины — сохранить и вывести с точностью до двух знаков запятой для удобства).

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../kinopoisk-top250.csv')
display(df.describe())  
display(df.info())

           rating         year  rating_ball
count  250.000000   250.000000   250.000000
mean   124.500000  1991.736000     8.231444
std     72.312977    19.015168     0.230376
min      0.000000  1921.000000     7.806000
25%     62.250000  1980.000000     8.063500
50%    124.500000  1997.500000     8.169000
75%    186.750000  2005.000000     8.355750
max    249.000000  2019.000000     9.111000

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rating        250 non-null    int64
 1   movie         250 non-null    str
 2   year          250 non-null    int64
 3   country       250 non-null    str
 4   rating_ball   250 non-null    float64
 5   overview      250 non-null    str
 6   director      250 non-null    str
 7   screenwriter  250 non-null    str
 8   actors        250 non-null    str
 9   url_logo      250 non-null    str
dtypes: float64(1), int64(2), str(7)
memory usage: 19.7 KB

None

Десять самых старых фильмов

In [4]:
ten_eldest = df.sort_values('year')[['movie', 'year']][:10]
display(ten_eldest)

                                movie  year
78                             Малыш   1921
221                Золотая лихорадка   1925
201                             Цирк   1928
45              Огни большого города   1931
121                    Новые времена   1936
89                  Унесенные ветром   1939
49           Эта замечательная жизнь   1947
234                Поющие под дождем   1952
88                  Римские каникулы   1953
157  В случае убийства набирайте «М»   1954

Сколько фильмов вышло в 1994 году.

In [5]:
films_in_1994 = df[df['year'] == 1994]
cnt = films_in_1994.shape[0]
display(cnt)

5

Фильмы Франции с рейтингом выше 8.0.

In [6]:
france_good_films = df[(df['country'] == 'Франция') & (df['rating'] > 8.0)]
display(france_good_films)

,rating,movie,year,country,rating_ball,overview,director,screenwriter,actors,url_logo
51,51,Хористы,2004,Франция,8.277,Франция; 1949 год. Отчаявшись найти работу; уч...,Кристоф Барратье,Рене Велер; Кристоф Барратье; Ноэль-Ноэль; ...,Жерар Жюньо; Франсуа Берлеан; Кад Мерад; Жан-П...,'https://st.kp.yandex.net/images/film_iphone/i...
112,112,Пятый элемент,1997,Франция,8.075,Каждые пять тысяч лет открываются двери между ...,Люк Бессон,Люк Бессон; Роберт Марк Кэмен,Брюс Уиллис; Милла Йовович; Гари Олдман; Иэн Х...,'https://st.kp.yandex.net/images/film_iphone/i...
117,117,Артист,2011,Франция,7.942,Голливуд; 1927 год. Звезда немого кино Джордж ...,Мишель Хазанавичус,Мишель Хазанавичус,Жан Дюжарден; Беренис Бежо; Джон Гудман; Джейм...,'https://st.kp.yandex.net/images/film_iphone/i...
155,155,Амели,2001,Франция,7.996,Знаете ли вы; что все события; происходящие в ...,Жан-Пьер Жёне,Гийом Лоран; Жан-Пьер Жёне,Одри Тоту; Матьё Кассовиц; Рюфюс; Лорелла Крав...,'https://st.kp.yandex.net/images/film_iphone/i...
218,218,Медведь,1988,Франция,7.993,Среди прекрасных и величественных пейзажей Бри...,Жан-Жак Анно,Жерар Браш; Джеймс Оливер Кёрвуд,медведь Барт; Чеки Карио; Джек Уоллес; Андре Л...,'https://st.kp.yandex.net/images/film_iphone/i...
248,248,Профессионал,1981,Франция,8.112,Убить президента африканской республики. Такое...,Жорж Лотнер,Мишель Одиар; Патрик Александер; Жорж Лотне...,Жан-Поль Бельмондо; Жан Дезайи; Сирил Клер; Ма...,'https://st.kp.yandex.net/images/film_iphone/i...

Фильмы с названием длиннее 15 символов.

In [17]:
long_name_movies = df[df['movie'].str.len() > 15]
display(long_name_movies['movie'])

0                          Побег из Шоушенка
3                            Список Шиндлера
8                            Бойцовский клуб
9           Иван Васильевич меняет профессию
10                           Жизнь прекрасна
                        ...
241                 Аты-баты; шли солдаты...
242           История игрушек: Большой побег
245                    Крамер против Крамера
246    Пираты Карибского моря: На краю Света
249      Холодное лето пятьдесят третьего...
Name: movie, Length: 128, dtype: str

Сколько фильмов снято в каждой стране (value_counts)

In [20]:
grouped_by_country = df.groupby('country')['movie'].count()
display(grouped_by_country)

country
Бразилия            1
Великобритания     15
Германия            6
Гонконг             1
Дания               1
Индия               3
Ирландия            1
Испания             1
Италия              7
Канада              1
Новая Зеландия      3
Польша              2
Россия              4
СССР               41
США               147
Франция             8
Эстония             1
Япония              7
Name: movie, dtype: int64

Топ-5 режиссёров по числу фильмов в рейтинге

In [26]:
# display(df.head(2))
directors = df.groupby('director').count()
display(directors.sort_values(by='movie', ascending=False)['movie'])

director
Игорь Масленников                7
Дэвид Финчер                     5
Роберт Земекис                   5
Стивен Спилберг                  5
Чарльз Чаплин                    5
                                ..
Эндрю Стэнтон                    1
Эрик Бресс;  Дж. Макки Грубер    1
Юрий Быков                       1
Юрий Кара                        1
Юрий Чулюкин                     1
Name: movie, Length: 170, dtype: int64

И ещё немного практики:

- Три года, в которые вышло больше всего фильмов.
- Фильмы, в описании которых встречается слово «любовь».
- Средний рейтинг фильмов до 1980 года и после 2000 года (результат — обе величины — сохранить и вывести с точностью до двух знаков запятой для удобства).

In [32]:
max_movies_years = df.groupby('year')['movie'].count()    # .idxmax()
display(max_movies_years.sort_values(ascending=False).head(5))

year
2001    11
2004    10
1997    10
2008    10
2005     8
Name: movie, dtype: int64

In [37]:
movies_about_love = df[df['overview'].str.contains('любовь')]
display(movies_about_love['movie'])

28                   В бой идут одни «старики»
66                      Москва слезам не верит
89                            Унесенные ветром
117                                     Артист
130                            Меня зовут Кхан
138                                   Терминал
150                          Ромео и Джульетта
172    Звёздные войны: Эпизод 3 – Месть Ситхов
220                                 Три идиота
Name: movie, dtype: str

In [40]:
avg_rating_before_1980 = df[df['year'] < 1980]['rating_ball'].mean()
avg_rating_after_2000 = df[df['year'] > 2000]['rating_ball'].mean()
display(round(avg_rating_before_1980, 2), round(avg_rating_after_2000, 2))

np.float64(8.31)

np.float64(8.16)